// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: scada-layout/proto/scada-layout.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFieldListRequest_RequestType int32

const (
	GetFieldListRequest_Tv    GetFieldListRequest_RequestType = 0
	GetFieldListRequest_Floor GetFieldListRequest_RequestType = 1
)

// Enum value maps for GetFieldListRequest_RequestType.
var (
	GetFieldListRequest_RequestType_name = map[int32]string{
		0: "Tv",
		1: "Floor",
	}
	GetFieldListRequest_RequestType_value = map[string]int32{
		"Tv":    0,
		"Floor": 1,
	}
)

func (x GetFieldListRequest_RequestType) Enum() *GetFieldListRequest_RequestType {
	p := new(GetFieldListRequest_RequestType)
	*p = x
	return p
}

func (x GetFieldListRequest_RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetFieldListRequest_RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_scada_layout_proto_scada_layout_proto_enumTypes[0].Descriptor()
}

func (GetFieldListRequest_RequestType) Type() protoreflect.EnumType {
	return &file_scada_layout_proto_scada_layout_proto_enumTypes[0]
}

func (x GetFieldListRequest_RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetFieldListRequest_RequestType.Descriptor instead.
func (GetFieldListRequest_RequestType) EnumDescriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{3, 0}
}

type FieldList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *FieldList) Reset() {
	*x = FieldList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldList) ProtoMessage() {}

func (x *FieldList) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldList.ProtoReflect.Descriptor instead.
func (*FieldList) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{0}
}

func (x *FieldList) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetFieldsTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldTags []*GetFieldsTagsResponse_FieldTag `protobuf:"bytes,1,rep,name=fieldTags,proto3" json:"fieldTags,omitempty"`
}

func (x *GetFieldsTagsResponse) Reset() {
	*x = GetFieldsTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldsTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsTagsResponse) ProtoMessage() {}

func (x *GetFieldsTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsTagsResponse.ProtoReflect.Descriptor instead.
func (*GetFieldsTagsResponse) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{1}
}

func (x *GetFieldsTagsResponse) GetFieldTags() []*GetFieldsTagsResponse_FieldTag {
	if x != nil {
		return x.FieldTags
	}
	return nil
}

type GetReportFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectName string                           `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Fields      []*GetReportFieldsResponse_Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetReportFieldsResponse) Reset() {
	*x = GetReportFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportFieldsResponse) ProtoMessage() {}

func (x *GetReportFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetReportFieldsResponse) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{2}
}

func (x *GetReportFieldsResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *GetReportFieldsResponse) GetFields() []*GetReportFieldsResponse_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetFieldListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type GetFieldListRequest_RequestType `protobuf:"varint,2,opt,name=type,proto3,enum=scada_layout.GetFieldListRequest_RequestType" json:"type,omitempty"`
}

func (x *GetFieldListRequest) Reset() {
	*x = GetFieldListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldListRequest) ProtoMessage() {}

func (x *GetFieldListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldListRequest.ProtoReflect.Descriptor instead.
func (*GetFieldListRequest) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{3}
}

func (x *GetFieldListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetFieldListRequest) GetType() GetFieldListRequest_RequestType {
	if x != nil {
		return x.Type
	}
	return GetFieldListRequest_Tv
}

type GetFieldListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetFieldListResponse) Reset() {
	*x = GetFieldListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldListResponse) ProtoMessage() {}

func (x *GetFieldListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldListResponse.ProtoReflect.Descriptor instead.
func (*GetFieldListResponse) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{4}
}

func (x *GetFieldListResponse) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetFieldsTagsResponse_FieldTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field      string                              `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Equipments []*GetFieldsTagsResponse_IdWithName `protobuf:"bytes,2,rep,name=equipments,proto3" json:"equipments,omitempty"`
	Groups     []*GetFieldsTagsResponse_IdWithName `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Floors     []*GetFieldsTagsResponse_IdWithName `protobuf:"bytes,4,rep,name=floors,proto3" json:"floors,omitempty"`
	Unit       string                              `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	SensorType string                              `protobuf:"bytes,6,opt,name=sensorType,proto3" json:"sensorType,omitempty"`
	Name       string                              `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetFieldsTagsResponse_FieldTag) Reset() {
	*x = GetFieldsTagsResponse_FieldTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldsTagsResponse_FieldTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsTagsResponse_FieldTag) ProtoMessage() {}

func (x *GetFieldsTagsResponse_FieldTag) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsTagsResponse_FieldTag.ProtoReflect.Descriptor instead.
func (*GetFieldsTagsResponse_FieldTag) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetFieldsTagsResponse_FieldTag) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GetFieldsTagsResponse_FieldTag) GetEquipments() []*GetFieldsTagsResponse_IdWithName {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *GetFieldsTagsResponse_FieldTag) GetGroups() []*GetFieldsTagsResponse_IdWithName {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetFieldsTagsResponse_FieldTag) GetFloors() []*GetFieldsTagsResponse_IdWithName {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *GetFieldsTagsResponse_FieldTag) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetFieldsTagsResponse_FieldTag) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *GetFieldsTagsResponse_FieldTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetFieldsTagsResponse_IdWithName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetFieldsTagsResponse_IdWithName) Reset() {
	*x = GetFieldsTagsResponse_IdWithName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldsTagsResponse_IdWithName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsTagsResponse_IdWithName) ProtoMessage() {}

func (x *GetFieldsTagsResponse_IdWithName) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsTagsResponse_IdWithName.ProtoReflect.Descriptor instead.
func (*GetFieldsTagsResponse_IdWithName) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetFieldsTagsResponse_IdWithName) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetFieldsTagsResponse_IdWithName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetReportFieldsResponse_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field       string           `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Equipments  []string         `protobuf:"bytes,2,rep,name=equipments,proto3" json:"equipments,omitempty"`
	Groups      []string         `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Floors      []string         `protobuf:"bytes,4,rep,name=floors,proto3" json:"floors,omitempty"`
	Unit        string           `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	SensorType  string           `protobuf:"bytes,6,opt,name=sensorType,proto3" json:"sensorType,omitempty"`
	Name        string           `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	DisplayType string           `protobuf:"bytes,8,opt,name=displayType,proto3" json:"displayType,omitempty"`
	DisplayDp   uint32           `protobuf:"varint,9,opt,name=displayDp,proto3" json:"displayDp,omitempty"`
	Trans       map[int32]string `protobuf:"bytes,10,rep,name=trans,proto3" json:"trans,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetReportFieldsResponse_Field) Reset() {
	*x = GetReportFieldsResponse_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportFieldsResponse_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportFieldsResponse_Field) ProtoMessage() {}

func (x *GetReportFieldsResponse_Field) ProtoReflect() protoreflect.Message {
	mi := &file_scada_layout_proto_scada_layout_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportFieldsResponse_Field.ProtoReflect.Descriptor instead.
func (*GetReportFieldsResponse_Field) Descriptor() ([]byte, []int) {
	return file_scada_layout_proto_scada_layout_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetReportFieldsResponse_Field) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GetReportFieldsResponse_Field) GetEquipments() []string {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *GetReportFieldsResponse_Field) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetReportFieldsResponse_Field) GetFloors() []string {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *GetReportFieldsResponse_Field) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetReportFieldsResponse_Field) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *GetReportFieldsResponse_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetReportFieldsResponse_Field) GetDisplayType() string {
	if x != nil {
		return x.DisplayType
	}
	return ""
}

func (x *GetReportFieldsResponse_Field) GetDisplayDp() uint32 {
	if x != nil {
		return x.DisplayDp
	}
	return 0
}

func (x *GetReportFieldsResponse_Field) GetTrans() map[int32]string {
	if x != nil {
		return x.Trans
	}
	return nil
}

var File_scada_layout_proto_scada_layout_proto protoreflect.FileDescriptor

var file_scada_layout_proto_scada_layout_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x63, 0x61, 0x64, 0x61, 0x2d, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x61, 0x64, 0x61, 0x2d, 0x6c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x22, 0x23, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0xe0, 0x03, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x54, 0x61, 0x67, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x61, 0x67, 0x73,
	0x1a, 0xc8, 0x02, 0x0a, 0x08, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x61, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x4e, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x64, 0x57,
	0x69, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x54, 0x61, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x66,
	0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x63,
	0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x49, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x66, 0x6c, 0x6f,
	0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x30, 0x0a, 0x0a, 0x49,
	0x64, 0x57, 0x69, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x80, 0x04,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x63,
	0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x1a, 0xfd, 0x02, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x6f,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x44, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x44, 0x70, 0x12, 0x4c, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x8a, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x41, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x54, 0x76,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x2e, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x32, 0x96, 0x02,
	0x0a, 0x12, 0x53, 0x63, 0x61, 0x64, 0x61, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x54, 0x61, 0x67, 0x73, 0x12, 0x17, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x17, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61,
	0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x67, 0x65,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x12, 0x21, 0x2e,
	0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x73, 0x63, 0x61, 0x64, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x73, 0x63, 0x61, 0x64, 0x61, 0x2d,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_scada_layout_proto_scada_layout_proto_rawDescOnce sync.Once
	file_scada_layout_proto_scada_layout_proto_rawDescData = file_scada_layout_proto_scada_layout_proto_rawDesc
)

func file_scada_layout_proto_scada_layout_proto_rawDescGZIP() []byte {
	file_scada_layout_proto_scada_layout_proto_rawDescOnce.Do(func() {
		file_scada_layout_proto_scada_layout_proto_rawDescData = protoimpl.X.CompressGZIP(file_scada_layout_proto_scada_layout_proto_rawDescData)
	})
	return file_scada_layout_proto_scada_layout_proto_rawDescData
}

var file_scada_layout_proto_scada_layout_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scada_layout_proto_scada_layout_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scada_layout_proto_scada_layout_proto_goTypes = []interface{}{
	(GetFieldListRequest_RequestType)(0),     // 0: scada_layout.GetFieldListRequest.RequestType
	(*FieldList)(nil),                        // 1: scada_layout.FieldList
	(*GetFieldsTagsResponse)(nil),            // 2: scada_layout.GetFieldsTagsResponse
	(*GetReportFieldsResponse)(nil),          // 3: scada_layout.GetReportFieldsResponse
	(*GetFieldListRequest)(nil),              // 4: scada_layout.GetFieldListRequest
	(*GetFieldListResponse)(nil),             // 5: scada_layout.GetFieldListResponse
	(*GetFieldsTagsResponse_FieldTag)(nil),   // 6: scada_layout.GetFieldsTagsResponse.FieldTag
	(*GetFieldsTagsResponse_IdWithName)(nil), // 7: scada_layout.GetFieldsTagsResponse.IdWithName
	(*GetReportFieldsResponse_Field)(nil),    // 8: scada_layout.GetReportFieldsResponse.Field
	nil,                                      // 9: scada_layout.GetReportFieldsResponse.Field.TransEntry
}
var file_scada_layout_proto_scada_layout_proto_depIdxs = []int32{
	6,  // 0: scada_layout.GetFieldsTagsResponse.fieldTags:type_name -> scada_layout.GetFieldsTagsResponse.FieldTag
	8,  // 1: scada_layout.GetReportFieldsResponse.fields:type_name -> scada_layout.GetReportFieldsResponse.Field
	0,  // 2: scada_layout.GetFieldListRequest.type:type_name -> scada_layout.GetFieldListRequest.RequestType
	7,  // 3: scada_layout.GetFieldsTagsResponse.FieldTag.equipments:type_name -> scada_layout.GetFieldsTagsResponse.IdWithName
	7,  // 4: scada_layout.GetFieldsTagsResponse.FieldTag.groups:type_name -> scada_layout.GetFieldsTagsResponse.IdWithName
	7,  // 5: scada_layout.GetFieldsTagsResponse.FieldTag.floors:type_name -> scada_layout.GetFieldsTagsResponse.IdWithName
	9,  // 6: scada_layout.GetReportFieldsResponse.Field.trans:type_name -> scada_layout.GetReportFieldsResponse.Field.TransEntry
	1,  // 7: scada_layout.ScadaLayoutService.getFieldsTags:input_type -> scada_layout.FieldList
	1,  // 8: scada_layout.ScadaLayoutService.getReportFields:input_type -> scada_layout.FieldList
	4,  // 9: scada_layout.ScadaLayoutService.getFieldsWithId:input_type -> scada_layout.GetFieldListRequest
	2,  // 10: scada_layout.ScadaLayoutService.getFieldsTags:output_type -> scada_layout.GetFieldsTagsResponse
	3,  // 11: scada_layout.ScadaLayoutService.getReportFields:output_type -> scada_layout.GetReportFieldsResponse
	5,  // 12: scada_layout.ScadaLayoutService.getFieldsWithId:output_type -> scada_layout.GetFieldListResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_scada_layout_proto_scada_layout_proto_init() }
func file_scada_layout_proto_scada_layout_proto_init() {
	if File_scada_layout_proto_scada_layout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scada_layout_proto_scada_layout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_layout_proto_scada_layout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldsTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_layout_proto_scada_layout_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_layout_proto_scada_layout_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_layout_proto_scada_layout_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_layout_proto_scada_layout_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldsTagsResponse_FieldTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_layout_proto_scada_layout_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldsTagsResponse_IdWithName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_layout_proto_scada_layout_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportFieldsResponse_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scada_layout_proto_scada_layout_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scada_layout_proto_scada_layout_proto_goTypes,
		DependencyIndexes: file_scada_layout_proto_scada_layout_proto_depIdxs,
		EnumInfos:         file_scada_layout_proto_scada_layout_proto_enumTypes,
		MessageInfos:      file_scada_layout_proto_scada_layout_proto_msgTypes,
	}.Build()
	File_scada_layout_proto_scada_layout_proto = out.File
	file_scada_layout_proto_scada_layout_proto_rawDesc = nil
	file_scada_layout_proto_scada_layout_proto_goTypes = nil
	file_scada_layout_proto_scada_layout_proto_depIdxs = nil
}
