// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: channel/proto/channel_report.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountSensorWarningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorIds []string `protobuf:"bytes,1,rep,name=sensorIds,proto3" json:"sensorIds,omitempty"`
}

func (x *CountSensorWarningRequest) Reset() {
	*x = CountSensorWarningRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channel_proto_channel_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountSensorWarningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountSensorWarningRequest) ProtoMessage() {}

func (x *CountSensorWarningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_channel_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountSensorWarningRequest.ProtoReflect.Descriptor instead.
func (*CountSensorWarningRequest) Descriptor() ([]byte, []int) {
	return file_channel_proto_channel_report_proto_rawDescGZIP(), []int{0}
}

func (x *CountSensorWarningRequest) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

type CountSensorWarningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[string]int64 `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *CountSensorWarningResponse) Reset() {
	*x = CountSensorWarningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channel_proto_channel_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountSensorWarningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountSensorWarningResponse) ProtoMessage() {}

func (x *CountSensorWarningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_channel_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountSensorWarningResponse.ProtoReflect.Descriptor instead.
func (*CountSensorWarningResponse) Descriptor() ([]byte, []int) {
	return file_channel_proto_channel_report_proto_rawDescGZIP(), []int{1}
}

func (x *CountSensorWarningResponse) GetResult() map[string]int64 {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_channel_proto_channel_report_proto protoreflect.FileDescriptor

var file_channel_proto_channel_report_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x39, 0x0a,
	0x19, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x57, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x57, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x1a, 0x39, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x71, 0x0a, 0x0d, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x13,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x57, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x12, 0x22, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x57, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c,
	0x5a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_channel_proto_channel_report_proto_rawDescOnce sync.Once
	file_channel_proto_channel_report_proto_rawDescData = file_channel_proto_channel_report_proto_rawDesc
)

func file_channel_proto_channel_report_proto_rawDescGZIP() []byte {
	file_channel_proto_channel_report_proto_rawDescOnce.Do(func() {
		file_channel_proto_channel_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_channel_proto_channel_report_proto_rawDescData)
	})
	return file_channel_proto_channel_report_proto_rawDescData
}

var file_channel_proto_channel_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_channel_proto_channel_report_proto_goTypes = []interface{}{
	(*CountSensorWarningRequest)(nil),  // 0: channel.CountSensorWarningRequest
	(*CountSensorWarningResponse)(nil), // 1: channel.CountSensorWarningResponse
	nil,                                // 2: channel.CountSensorWarningResponse.ResultEntry
}
var file_channel_proto_channel_report_proto_depIdxs = []int32{
	2, // 0: channel.CountSensorWarningResponse.result:type_name -> channel.CountSensorWarningResponse.ResultEntry
	0, // 1: channel.ReportService.CountSensorsWarning:input_type -> channel.CountSensorWarningRequest
	1, // 2: channel.ReportService.CountSensorsWarning:output_type -> channel.CountSensorWarningResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_channel_proto_channel_report_proto_init() }
func file_channel_proto_channel_report_proto_init() {
	if File_channel_proto_channel_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_channel_proto_channel_report_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountSensorWarningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channel_proto_channel_report_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountSensorWarningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_channel_proto_channel_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_proto_channel_report_proto_goTypes,
		DependencyIndexes: file_channel_proto_channel_report_proto_depIdxs,
		MessageInfos:      file_channel_proto_channel_report_proto_msgTypes,
	}.Build()
	File_channel_proto_channel_report_proto = out.File
	file_channel_proto_channel_report_proto_rawDesc = nil
	file_channel_proto_channel_report_proto_goTypes = nil
	file_channel_proto_channel_report_proto_depIdxs = nil
}
