syntax = "proto3";

option go_package = "scada-event/pb";
package scada_event;

import "google/protobuf/empty.proto";


message FieldInfo {
    string name = 1;
    string field = 2;
    bool sound_on = 3;
}
message CreateWarningsReq {
    
    message Warning { 
        string key = 1;
        string name = 2;
        FieldInfo field = 3;
        bytes data = 4;
        bytes detail = 5;
    }

    string service = 1;
    repeated Warning warnings = 2;
}

message CloseWarningReq {
    string service = 1;
    repeated string key = 2;
}

message GetRealtimeReq {
    string service = 1;
}

message GetRealtimeResp {
    message ReaderInfo {
        string account = 1;
        int64 timestamp = 2;
    }
    message Warning { 
        string key = 1;
        string name = 2;
        FieldInfo field = 3;
        int64 create_time = 4;
        bytes detail = 5;
        repeated ReaderInfo readers = 6;
    }
    repeated Warning warnings = 1;
}

message ExtendWarningReq {
    string service = 1;
    repeated string key = 2;
}

message ReadWarningsReq {
    string service = 1;
    repeated string key = 2;
    string account = 3;
}

message CreateEventReq {
    string service = 1;
    string type = 2;
    string summarize = 3;
    string detail = 4;
}

message CreateSystemNoticeReq {
    string service = 1;
    string type = 2;
    bytes values = 3;
    bool retain = 4;
    string summarize = 5;
    string detail = 6;
}

service ScadaEventService {
    rpc CreateWarning(CreateWarningsReq) returns (google.protobuf.Empty) {}
    rpc CloseWarning(CloseWarningReq) returns (google.protobuf.Empty) {}
    rpc ExtendWarning(ExtendWarningReq) returns (google.protobuf.Empty) {}
    rpc ReadWarnings(ReadWarningsReq) returns (google.protobuf.Empty) {}
    rpc GetRealtime(GetRealtimeReq) returns (GetRealtimeResp) {}
    rpc CreateEvent(CreateEventReq) returns (google.protobuf.Empty) {}
    rpc CreateSystemNotice(CreateSystemNoticeReq) returns (google.protobuf.Empty) {}
}
