// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: auth/proto/auth_migration.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationUserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string                                    `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Email   string                                    `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Pwd     string                                    `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Name    string                                    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Perms   []*MigrationUserInfoRequest_Perm          `protobuf:"bytes,5,rep,name=perms,proto3" json:"perms,omitempty"`
	Folders []*MigrationUserInfoRequest_ProjectFolder `protobuf:"bytes,6,rep,name=folders,proto3" json:"folders,omitempty"`
}

func (x *MigrationUserInfoRequest) Reset() {
	*x = MigrationUserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_auth_migration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationUserInfoRequest) ProtoMessage() {}

func (x *MigrationUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_migration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationUserInfoRequest.ProtoReflect.Descriptor instead.
func (*MigrationUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationUserInfoRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MigrationUserInfoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MigrationUserInfoRequest) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *MigrationUserInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationUserInfoRequest) GetPerms() []*MigrationUserInfoRequest_Perm {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *MigrationUserInfoRequest) GetFolders() []*MigrationUserInfoRequest_ProjectFolder {
	if x != nil {
		return x.Folders
	}
	return nil
}

type MigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode uint32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MigrationResponse) Reset() {
	*x = MigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_auth_migration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationResponse) ProtoMessage() {}

func (x *MigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_migration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationResponse.ProtoReflect.Descriptor instead.
func (*MigrationResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_migration_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MigrationUserInfoRequest_Perm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Syscode string `protobuf:"bytes,1,opt,name=syscode,proto3" json:"syscode,omitempty"`
	Group   string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *MigrationUserInfoRequest_Perm) Reset() {
	*x = MigrationUserInfoRequest_Perm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_auth_migration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationUserInfoRequest_Perm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationUserInfoRequest_Perm) ProtoMessage() {}

func (x *MigrationUserInfoRequest_Perm) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_migration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationUserInfoRequest_Perm.ProtoReflect.Descriptor instead.
func (*MigrationUserInfoRequest_Perm) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_migration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MigrationUserInfoRequest_Perm) GetSyscode() string {
	if x != nil {
		return x.Syscode
	}
	return ""
}

func (x *MigrationUserInfoRequest_Perm) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type MigrationUserInfoRequest_ProjectFolder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProjectIds []string `protobuf:"bytes,2,rep,name=projectIds,proto3" json:"projectIds,omitempty"`
}

func (x *MigrationUserInfoRequest_ProjectFolder) Reset() {
	*x = MigrationUserInfoRequest_ProjectFolder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_auth_migration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationUserInfoRequest_ProjectFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationUserInfoRequest_ProjectFolder) ProtoMessage() {}

func (x *MigrationUserInfoRequest_ProjectFolder) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_migration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationUserInfoRequest_ProjectFolder.ProtoReflect.Descriptor instead.
func (*MigrationUserInfoRequest_ProjectFolder) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_migration_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MigrationUserInfoRequest_ProjectFolder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationUserInfoRequest_ProjectFolder) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

var File_auth_proto_auth_migration_proto protoreflect.FileDescriptor

var file_auth_proto_auth_migration_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0xf0, 0x02, 0x0a, 0x18, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x70, 0x65,
	0x72, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x52, 0x05,
	0x70, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x46, 0x0a, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x52, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x36, 0x0a,
	0x04, 0x50, 0x65, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x43, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x11, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x6a, 0x0a, 0x14, 0x41, 0x75, 0x74,
	0x68, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x52, 0x0a, 0x11, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_proto_auth_migration_proto_rawDescOnce sync.Once
	file_auth_proto_auth_migration_proto_rawDescData = file_auth_proto_auth_migration_proto_rawDesc
)

func file_auth_proto_auth_migration_proto_rawDescGZIP() []byte {
	file_auth_proto_auth_migration_proto_rawDescOnce.Do(func() {
		file_auth_proto_auth_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_proto_auth_migration_proto_rawDescData)
	})
	return file_auth_proto_auth_migration_proto_rawDescData
}

var file_auth_proto_auth_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_proto_auth_migration_proto_goTypes = []interface{}{
	(*MigrationUserInfoRequest)(nil),               // 0: auth.MigrationUserInfoRequest
	(*MigrationResponse)(nil),                      // 1: auth.MigrationResponse
	(*MigrationUserInfoRequest_Perm)(nil),          // 2: auth.MigrationUserInfoRequest.Perm
	(*MigrationUserInfoRequest_ProjectFolder)(nil), // 3: auth.MigrationUserInfoRequest.ProjectFolder
}
var file_auth_proto_auth_migration_proto_depIdxs = []int32{
	2, // 0: auth.MigrationUserInfoRequest.perms:type_name -> auth.MigrationUserInfoRequest.Perm
	3, // 1: auth.MigrationUserInfoRequest.folders:type_name -> auth.MigrationUserInfoRequest.ProjectFolder
	0, // 2: auth.AuthMigrationService.MigrationUserInfo:input_type -> auth.MigrationUserInfoRequest
	1, // 3: auth.AuthMigrationService.MigrationUserInfo:output_type -> auth.MigrationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_proto_auth_migration_proto_init() }
func file_auth_proto_auth_migration_proto_init() {
	if File_auth_proto_auth_migration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_proto_auth_migration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationUserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_proto_auth_migration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_proto_auth_migration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationUserInfoRequest_Perm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_proto_auth_migration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationUserInfoRequest_ProjectFolder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_proto_auth_migration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_auth_migration_proto_goTypes,
		DependencyIndexes: file_auth_proto_auth_migration_proto_depIdxs,
		MessageInfos:      file_auth_proto_auth_migration_proto_msgTypes,
	}.Build()
	File_auth_proto_auth_migration_proto = out.File
	file_auth_proto_auth_migration_proto_rawDesc = nil
	file_auth_proto_auth_migration_proto_goTypes = nil
	file_auth_proto_auth_migration_proto_depIdxs = nil
}
