// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: maintenance/proto/maintenance_migration.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode uint32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MigrationResponse) Reset() {
	*x = MigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationResponse) ProtoMessage() {}

func (x *MigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationResponse.ProtoReflect.Descriptor instead.
func (*MigrationResponse) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_maintenance_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MigrationMaintenanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         string                                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	OtherDesc    string                                 `protobuf:"bytes,3,opt,name=otherDesc,proto3" json:"otherDesc,omitempty"`
	Reportor     string                                 `protobuf:"bytes,4,opt,name=reportor,proto3" json:"reportor,omitempty"`
	CreateTime   int64                                  `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	CreateUser   *MigrationMaintenanceRequest_User      `protobuf:"bytes,6,opt,name=createUser,proto3" json:"createUser,omitempty"`
	ArrivalTime  int64                                  `protobuf:"varint,7,opt,name=arrivalTime,proto3" json:"arrivalTime,omitempty"`
	CompleteTime int64                                  `protobuf:"varint,8,opt,name=completeTime,proto3" json:"completeTime,omitempty"`
	CompleteUser *MigrationMaintenanceRequest_User      `protobuf:"bytes,9,opt,name=completeUser,proto3" json:"completeUser,omitempty"`
	IsMistake    bool                                   `protobuf:"varint,10,opt,name=isMistake,proto3" json:"isMistake,omitempty"`
	State        string                                 `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	EquipId      string                                 `protobuf:"bytes,12,opt,name=equipId,proto3" json:"equipId,omitempty"`
	Sensor       *MigrationMaintenanceRequest_Sensor    `protobuf:"bytes,13,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Comments     []*MigrationMaintenanceRequest_Comment `protobuf:"bytes,14,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (x *MigrationMaintenanceRequest) Reset() {
	*x = MigrationMaintenanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationMaintenanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationMaintenanceRequest) ProtoMessage() {}

func (x *MigrationMaintenanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationMaintenanceRequest.ProtoReflect.Descriptor instead.
func (*MigrationMaintenanceRequest) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_maintenance_migration_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationMaintenanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MigrationMaintenanceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MigrationMaintenanceRequest) GetOtherDesc() string {
	if x != nil {
		return x.OtherDesc
	}
	return ""
}

func (x *MigrationMaintenanceRequest) GetReportor() string {
	if x != nil {
		return x.Reportor
	}
	return ""
}

func (x *MigrationMaintenanceRequest) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *MigrationMaintenanceRequest) GetCreateUser() *MigrationMaintenanceRequest_User {
	if x != nil {
		return x.CreateUser
	}
	return nil
}

func (x *MigrationMaintenanceRequest) GetArrivalTime() int64 {
	if x != nil {
		return x.ArrivalTime
	}
	return 0
}

func (x *MigrationMaintenanceRequest) GetCompleteTime() int64 {
	if x != nil {
		return x.CompleteTime
	}
	return 0
}

func (x *MigrationMaintenanceRequest) GetCompleteUser() *MigrationMaintenanceRequest_User {
	if x != nil {
		return x.CompleteUser
	}
	return nil
}

func (x *MigrationMaintenanceRequest) GetIsMistake() bool {
	if x != nil {
		return x.IsMistake
	}
	return false
}

func (x *MigrationMaintenanceRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MigrationMaintenanceRequest) GetEquipId() string {
	if x != nil {
		return x.EquipId
	}
	return ""
}

func (x *MigrationMaintenanceRequest) GetSensor() *MigrationMaintenanceRequest_Sensor {
	if x != nil {
		return x.Sensor
	}
	return nil
}

func (x *MigrationMaintenanceRequest) GetComments() []*MigrationMaintenanceRequest_Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type MigrationMaintenanceRequest_Sensor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceNo int32 `protobuf:"varint,1,opt,name=deviceNo,proto3" json:"deviceNo,omitempty"`
	Address  int32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *MigrationMaintenanceRequest_Sensor) Reset() {
	*x = MigrationMaintenanceRequest_Sensor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationMaintenanceRequest_Sensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationMaintenanceRequest_Sensor) ProtoMessage() {}

func (x *MigrationMaintenanceRequest_Sensor) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationMaintenanceRequest_Sensor.ProtoReflect.Descriptor instead.
func (*MigrationMaintenanceRequest_Sensor) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_maintenance_migration_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MigrationMaintenanceRequest_Sensor) GetDeviceNo() int32 {
	if x != nil {
		return x.DeviceNo
	}
	return 0
}

func (x *MigrationMaintenanceRequest_Sensor) GetAddress() int32 {
	if x != nil {
		return x.Address
	}
	return 0
}

type MigrationMaintenanceRequest_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *MigrationMaintenanceRequest_User) Reset() {
	*x = MigrationMaintenanceRequest_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationMaintenanceRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationMaintenanceRequest_User) ProtoMessage() {}

func (x *MigrationMaintenanceRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationMaintenanceRequest_User.ProtoReflect.Descriptor instead.
func (*MigrationMaintenanceRequest_User) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_maintenance_migration_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MigrationMaintenanceRequest_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationMaintenanceRequest_User) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MigrationMaintenanceRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MigrationMaintenanceRequest_Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateUnix int64                             `protobuf:"varint,1,opt,name=dateUnix,proto3" json:"dateUnix,omitempty"`
	Message  string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User     *MigrationMaintenanceRequest_User `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *MigrationMaintenanceRequest_Comment) Reset() {
	*x = MigrationMaintenanceRequest_Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationMaintenanceRequest_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationMaintenanceRequest_Comment) ProtoMessage() {}

func (x *MigrationMaintenanceRequest_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_maintenance_migration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationMaintenanceRequest_Comment.ProtoReflect.Descriptor instead.
func (*MigrationMaintenanceRequest_Comment) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_maintenance_migration_proto_rawDescGZIP(), []int{1, 2}
}

func (x *MigrationMaintenanceRequest_Comment) GetDateUnix() int64 {
	if x != nil {
		return x.DateUnix
	}
	return 0
}

func (x *MigrationMaintenanceRequest_Comment) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MigrationMaintenanceRequest_Comment) GetUser() *MigrationMaintenanceRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_maintenance_proto_maintenance_migration_proto protoreflect.FileDescriptor

var file_maintenance_proto_maintenance_migration_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x4d, 0x0a, 0x11,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf9, 0x06, 0x0a, 0x1b,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x44, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61,
	0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x51,
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x4d, 0x69, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x4d, 0x69, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12,
	0x47, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x4c, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x3e, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x4a, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x1a, 0x82, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0x85, 0x01, 0x0a, 0x1b, 0x4d, 0x61, 0x69, 0x6e,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x14, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x28, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x10, 0x5a, 0x0e, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maintenance_proto_maintenance_migration_proto_rawDescOnce sync.Once
	file_maintenance_proto_maintenance_migration_proto_rawDescData = file_maintenance_proto_maintenance_migration_proto_rawDesc
)

func file_maintenance_proto_maintenance_migration_proto_rawDescGZIP() []byte {
	file_maintenance_proto_maintenance_migration_proto_rawDescOnce.Do(func() {
		file_maintenance_proto_maintenance_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_maintenance_proto_maintenance_migration_proto_rawDescData)
	})
	return file_maintenance_proto_maintenance_migration_proto_rawDescData
}

var file_maintenance_proto_maintenance_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_maintenance_proto_maintenance_migration_proto_goTypes = []interface{}{
	(*MigrationResponse)(nil),                   // 0: maintenance.MigrationResponse
	(*MigrationMaintenanceRequest)(nil),         // 1: maintenance.MigrationMaintenanceRequest
	(*MigrationMaintenanceRequest_Sensor)(nil),  // 2: maintenance.MigrationMaintenanceRequest.Sensor
	(*MigrationMaintenanceRequest_User)(nil),    // 3: maintenance.MigrationMaintenanceRequest.User
	(*MigrationMaintenanceRequest_Comment)(nil), // 4: maintenance.MigrationMaintenanceRequest.Comment
}
var file_maintenance_proto_maintenance_migration_proto_depIdxs = []int32{
	3, // 0: maintenance.MigrationMaintenanceRequest.createUser:type_name -> maintenance.MigrationMaintenanceRequest.User
	3, // 1: maintenance.MigrationMaintenanceRequest.completeUser:type_name -> maintenance.MigrationMaintenanceRequest.User
	2, // 2: maintenance.MigrationMaintenanceRequest.sensor:type_name -> maintenance.MigrationMaintenanceRequest.Sensor
	4, // 3: maintenance.MigrationMaintenanceRequest.comments:type_name -> maintenance.MigrationMaintenanceRequest.Comment
	3, // 4: maintenance.MigrationMaintenanceRequest.Comment.user:type_name -> maintenance.MigrationMaintenanceRequest.User
	1, // 5: maintenance.MaintenanceMigrationService.MigrationMaintenance:input_type -> maintenance.MigrationMaintenanceRequest
	0, // 6: maintenance.MaintenanceMigrationService.MigrationMaintenance:output_type -> maintenance.MigrationResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_maintenance_proto_maintenance_migration_proto_init() }
func file_maintenance_proto_maintenance_migration_proto_init() {
	if File_maintenance_proto_maintenance_migration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maintenance_proto_maintenance_migration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maintenance_proto_maintenance_migration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationMaintenanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maintenance_proto_maintenance_migration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationMaintenanceRequest_Sensor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maintenance_proto_maintenance_migration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationMaintenanceRequest_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maintenance_proto_maintenance_migration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationMaintenanceRequest_Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maintenance_proto_maintenance_migration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maintenance_proto_maintenance_migration_proto_goTypes,
		DependencyIndexes: file_maintenance_proto_maintenance_migration_proto_depIdxs,
		MessageInfos:      file_maintenance_proto_maintenance_migration_proto_msgTypes,
	}.Build()
	File_maintenance_proto_maintenance_migration_proto = out.File
	file_maintenance_proto_maintenance_migration_proto_rawDesc = nil
	file_maintenance_proto_maintenance_migration_proto_goTypes = nil
	file_maintenance_proto_maintenance_migration_proto_depIdxs = nil
}
