// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: device/app/proto/device.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppDeviceServiceClient is the client API for AppDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppDeviceServiceClient interface {
	AssignDevices(ctx context.Context, in *AssignDevicesRequest, opts ...grpc.CallOption) (AppDeviceService_AssignDevicesClient, error)
}

type appDeviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppDeviceServiceClient(cc grpc.ClientConnInterface) AppDeviceServiceClient {
	return &appDeviceServiceClient{cc}
}

func (c *appDeviceServiceClient) AssignDevices(ctx context.Context, in *AssignDevicesRequest, opts ...grpc.CallOption) (AppDeviceService_AssignDevicesClient, error) {
	stream, err := c.cc.NewStream(ctx, &AppDeviceService_ServiceDesc.Streams[0], "/service.AppDeviceService/AssignDevices", opts...)
	if err != nil {
		return nil, err
	}
	x := &appDeviceServiceAssignDevicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AppDeviceService_AssignDevicesClient interface {
	Recv() (*AssignDeviceResponse, error)
	grpc.ClientStream
}

type appDeviceServiceAssignDevicesClient struct {
	grpc.ClientStream
}

func (x *appDeviceServiceAssignDevicesClient) Recv() (*AssignDeviceResponse, error) {
	m := new(AssignDeviceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppDeviceServiceServer is the server API for AppDeviceService service.
// All implementations must embed UnimplementedAppDeviceServiceServer
// for forward compatibility
type AppDeviceServiceServer interface {
	AssignDevices(*AssignDevicesRequest, AppDeviceService_AssignDevicesServer) error
	mustEmbedUnimplementedAppDeviceServiceServer()
}

// UnimplementedAppDeviceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAppDeviceServiceServer struct {
}

func (UnimplementedAppDeviceServiceServer) AssignDevices(*AssignDevicesRequest, AppDeviceService_AssignDevicesServer) error {
	return status.Errorf(codes.Unimplemented, "method AssignDevices not implemented")
}
func (UnimplementedAppDeviceServiceServer) mustEmbedUnimplementedAppDeviceServiceServer() {}

// UnsafeAppDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppDeviceServiceServer will
// result in compilation errors.
type UnsafeAppDeviceServiceServer interface {
	mustEmbedUnimplementedAppDeviceServiceServer()
}

func RegisterAppDeviceServiceServer(s grpc.ServiceRegistrar, srv AppDeviceServiceServer) {
	s.RegisterService(&AppDeviceService_ServiceDesc, srv)
}

func _AppDeviceService_AssignDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AssignDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppDeviceServiceServer).AssignDevices(m, &appDeviceServiceAssignDevicesServer{stream})
}

type AppDeviceService_AssignDevicesServer interface {
	Send(*AssignDeviceResponse) error
	grpc.ServerStream
}

type appDeviceServiceAssignDevicesServer struct {
	grpc.ServerStream
}

func (x *appDeviceServiceAssignDevicesServer) Send(m *AssignDeviceResponse) error {
	return x.ServerStream.SendMsg(m)
}

// AppDeviceService_ServiceDesc is the grpc.ServiceDesc for AppDeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppDeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.AppDeviceService",
	HandlerType: (*AppDeviceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AssignDevices",
			Handler:       _AppDeviceService_AssignDevices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "device/app/proto/device.proto",
}
