// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: device/app/proto/device.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditType int32

const (
	EditType_Add EditType = 0
	EditType_Del EditType = 1
)

// Enum value maps for EditType.
var (
	EditType_name = map[int32]string{
		0: "Add",
		1: "Del",
	}
	EditType_value = map[string]int32{
		"Add": 0,
		"Del": 1,
	}
)

func (x EditType) Enum() *EditType {
	p := new(EditType)
	*p = x
	return p
}

func (x EditType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditType) Descriptor() protoreflect.EnumDescriptor {
	return file_device_app_proto_device_proto_enumTypes[0].Descriptor()
}

func (EditType) Type() protoreflect.EnumType {
	return &file_device_app_proto_device_proto_enumTypes[0]
}

func (x EditType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditType.Descriptor instead.
func (EditType) EnumDescriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{0}
}

type TxnType int32

const (
	TxnType_Sending   TxnType = 0
	TxnType_Recycling TxnType = 1
)

// Enum value maps for TxnType.
var (
	TxnType_name = map[int32]string{
		0: "Sending",
		1: "Recycling",
	}
	TxnType_value = map[string]int32{
		"Sending":   0,
		"Recycling": 1,
	}
)

func (x TxnType) Enum() *TxnType {
	p := new(TxnType)
	*p = x
	return p
}

func (x TxnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxnType) Descriptor() protoreflect.EnumDescriptor {
	return file_device_app_proto_device_proto_enumTypes[1].Descriptor()
}

func (TxnType) Type() protoreflect.EnumType {
	return &file_device_app_proto_device_proto_enumTypes[1]
}

func (x TxnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxnType.Descriptor instead.
func (TxnType) EnumDescriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{1}
}

type TxnState int32

const (
	TxnState_New       TxnState = 0
	TxnState_Confirmed TxnState = 1
	TxnState_Canceled  TxnState = 2
)

// Enum value maps for TxnState.
var (
	TxnState_name = map[int32]string{
		0: "New",
		1: "Confirmed",
		2: "Canceled",
	}
	TxnState_value = map[string]int32{
		"New":       0,
		"Confirmed": 1,
		"Canceled":  2,
	}
)

func (x TxnState) Enum() *TxnState {
	p := new(TxnState)
	*p = x
	return p
}

func (x TxnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxnState) Descriptor() protoreflect.EnumDescriptor {
	return file_device_app_proto_device_proto_enumTypes[2].Descriptor()
}

func (TxnState) Type() protoreflect.EnumType {
	return &file_device_app_proto_device_proto_enumTypes[2]
}

func (x TxnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxnState.Descriptor instead.
func (TxnState) EnumDescriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{2}
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mac       string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	VirtualID uint32 `protobuf:"varint,3,opt,name=virtualID,proto3" json:"virtualID,omitempty"`
	Model     string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Device) GetVirtualID() uint32 {
	if x != nil {
		return x.VirtualID
	}
	return 0
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type DeviceRelationEditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjID   string     `protobuf:"bytes,1,opt,name=objID,proto3" json:"objID,omitempty"`
	Actions []*EditObj `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *DeviceRelationEditRequest) Reset() {
	*x = DeviceRelationEditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceRelationEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRelationEditRequest) ProtoMessage() {}

func (x *DeviceRelationEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRelationEditRequest.ProtoReflect.Descriptor instead.
func (*DeviceRelationEditRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceRelationEditRequest) GetObjID() string {
	if x != nil {
		return x.ObjID
	}
	return ""
}

func (x *DeviceRelationEditRequest) GetActions() []*EditObj {
	if x != nil {
		return x.Actions
	}
	return nil
}

type EditObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Act      EditType `protobuf:"varint,1,opt,name=act,proto3,enum=service.EditType" json:"act,omitempty"`
	DeviceID string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
}

func (x *EditObj) Reset() {
	*x = EditObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditObj) ProtoMessage() {}

func (x *EditObj) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditObj.ProtoReflect.Descriptor instead.
func (*EditObj) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{2}
}

func (x *EditObj) GetAct() EditType {
	if x != nil {
		return x.Act
	}
	return EditType_Add
}

func (x *EditObj) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type DeviceRelationEditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeviceID string `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Error    string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeviceRelationEditResponse) Reset() {
	*x = DeviceRelationEditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceRelationEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRelationEditResponse) ProtoMessage() {}

func (x *DeviceRelationEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRelationEditResponse.ProtoReflect.Descriptor instead.
func (*DeviceRelationEditResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceRelationEditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeviceRelationEditResponse) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceRelationEditResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDevicesByEquipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipIDs []string `protobuf:"bytes,1,rep,name=equipIDs,proto3" json:"equipIDs,omitempty"`
}

func (x *GetDevicesByEquipsRequest) Reset() {
	*x = GetDevicesByEquipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesByEquipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesByEquipsRequest) ProtoMessage() {}

func (x *GetDevicesByEquipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesByEquipsRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesByEquipsRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{4}
}

func (x *GetDevicesByEquipsRequest) GetEquipIDs() []string {
	if x != nil {
		return x.EquipIDs
	}
	return nil
}

type GetDevicesByEquipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipID string        `protobuf:"bytes,1,opt,name=equipID,proto3" json:"equipID,omitempty"`
	Devices []*DeviceInfo `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *GetDevicesByEquipsResponse) Reset() {
	*x = GetDevicesByEquipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesByEquipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesByEquipsResponse) ProtoMessage() {}

func (x *GetDevicesByEquipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesByEquipsResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesByEquipsResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{5}
}

func (x *GetDevicesByEquipsResponse) GetEquipID() string {
	if x != nil {
		return x.EquipID
	}
	return ""
}

func (x *GetDevicesByEquipsResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MacAddress  string `protobuf:"bytes,2,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	VirtualID   uint32 `protobuf:"varint,3,opt,name=virtualID,proto3" json:"virtualID,omitempty"`
	State       string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Model       string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	OnlineState string `protobuf:"bytes,7,opt,name=onlineState,proto3" json:"onlineState,omitempty"`
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DeviceInfo) GetVirtualID() uint32 {
	if x != nil {
		return x.VirtualID
	}
	return 0
}

func (x *DeviceInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DeviceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetOnlineState() string {
	if x != nil {
		return x.OnlineState
	}
	return ""
}

type ModifySendTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransID string    `protobuf:"bytes,1,opt,name=transID,proto3" json:"transID,omitempty"`
	MacList []*ActTxn `protobuf:"bytes,2,rep,name=macList,proto3" json:"macList,omitempty"`
	Comment string    `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *ModifySendTxnRequest) Reset() {
	*x = ModifySendTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySendTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySendTxnRequest) ProtoMessage() {}

func (x *ModifySendTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySendTxnRequest.ProtoReflect.Descriptor instead.
func (*ModifySendTxnRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{7}
}

func (x *ModifySendTxnRequest) GetTransID() string {
	if x != nil {
		return x.TransID
	}
	return ""
}

func (x *ModifySendTxnRequest) GetMacList() []*ActTxn {
	if x != nil {
		return x.MacList
	}
	return nil
}

func (x *ModifySendTxnRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ActTxn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Act    EditType `protobuf:"varint,1,opt,name=act,proto3,enum=service.EditType" json:"act,omitempty"`
	Device *Device  `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *ActTxn) Reset() {
	*x = ActTxn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActTxn) ProtoMessage() {}

func (x *ActTxn) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActTxn.ProtoReflect.Descriptor instead.
func (*ActTxn) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{8}
}

func (x *ActTxn) GetAct() EditType {
	if x != nil {
		return x.Act
	}
	return EditType_Add
}

func (x *ActTxn) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type CreateSendTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Devices     []*Device              `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateSendTxnRequest) Reset() {
	*x = CreateSendTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSendTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSendTxnRequest) ProtoMessage() {}

func (x *CreateSendTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSendTxnRequest.ProtoReflect.Descriptor instead.
func (*CreateSendTxnRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSendTxnRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CreateSendTxnRequest) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *CreateSendTxnRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSendTxnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Device  *Device `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Error   string  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateSendTxnResponse) Reset() {
	*x = CreateSendTxnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSendTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSendTxnResponse) ProtoMessage() {}

func (x *CreateSendTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSendTxnResponse.ProtoReflect.Descriptor instead.
func (*CreateSendTxnResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSendTxnResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSendTxnResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *CreateSendTxnResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApplyTxn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ApplyTxn) Reset() {
	*x = ApplyTxn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTxn) ProtoMessage() {}

func (x *ApplyTxn) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTxn.ProtoReflect.Descriptor instead.
func (*ApplyTxn) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyTxn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplyTxn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type QueryTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      TxnType  `protobuf:"varint,1,opt,name=type,proto3,enum=service.TxnType" json:"type,omitempty"`
	State     TxnState `protobuf:"varint,2,opt,name=state,proto3,enum=service.TxnState" json:"state,omitempty"`
	StartTime string   `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string   `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *QueryTxnRequest) Reset() {
	*x = QueryTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTxnRequest) ProtoMessage() {}

func (x *QueryTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTxnRequest.ProtoReflect.Descriptor instead.
func (*QueryTxnRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{12}
}

func (x *QueryTxnRequest) GetType() TxnType {
	if x != nil {
		return x.Type
	}
	return TxnType_Sending
}

func (x *QueryTxnRequest) GetState() TxnState {
	if x != nil {
		return x.State
	}
	return TxnState_New
}

func (x *QueryTxnRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QueryTxnRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type QueryTxnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time        string     `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Devices     []*Device  `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	Description string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	State       string     `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Comments    []*Comment `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (x *QueryTxnResponse) Reset() {
	*x = QueryTxnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTxnResponse) ProtoMessage() {}

func (x *QueryTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTxnResponse.ProtoReflect.Descriptor instead.
func (*QueryTxnResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{13}
}

func (x *QueryTxnResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryTxnResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *QueryTxnResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *QueryTxnResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QueryTxnResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *QueryTxnResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Name    string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Comment) Reset() {
	*x = Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{14}
}

func (x *Comment) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Comment) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Comment) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Comment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TxnAddCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnID string `protobuf:"bytes,1,opt,name=txnID,proto3" json:"txnID,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TxnAddCommentRequest) Reset() {
	*x = TxnAddCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnAddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnAddCommentRequest) ProtoMessage() {}

func (x *TxnAddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnAddCommentRequest.ProtoReflect.Descriptor instead.
func (*TxnAddCommentRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{15}
}

func (x *TxnAddCommentRequest) GetTxnID() string {
	if x != nil {
		return x.TxnID
	}
	return ""
}

func (x *TxnAddCommentRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MigrationTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *MigrationTxnRequest) Reset() {
	*x = MigrationTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationTxnRequest) ProtoMessage() {}

func (x *MigrationTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationTxnRequest.ProtoReflect.Descriptor instead.
func (*MigrationTxnRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{16}
}

func (x *MigrationTxnRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MigrationTxnRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode uint32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{17}
}

func (x *CommonResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveTxnRequest) Reset() {
	*x = RemoveTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTxnRequest) ProtoMessage() {}

func (x *RemoveTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTxnRequest.ProtoReflect.Descriptor instead.
func (*RemoveTxnRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveTxnRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_device_app_proto_device_proto protoreflect.FileDescriptor

var file_device_app_proto_device_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x06, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x5d, 0x0a, 0x19, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x07,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x4f, 0x62, 0x6a, 0x52,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x07, 0x45, 0x64, 0x69, 0x74,
	0x4f, 0x62, 0x6a, 0x12, 0x23, 0x0a, 0x03, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x03, 0x61, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x44, 0x22, 0x68, 0x0a, 0x1a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x37,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x49, 0x44, 0x73, 0x22, 0x65, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x44, 0x12,
	0x2d, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xca,
	0x01, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x75, 0x0a, 0x14, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x44, 0x12, 0x29, 0x0a,
	0x07, 0x6d, 0x61, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x54, 0x78, 0x6e, 0x52,
	0x07, 0x6d, 0x61, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x56, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x54, 0x78, 0x6e, 0x12, 0x23, 0x0a, 0x03,
	0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x61, 0x63,
	0x74, 0x12, 0x27, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x70, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x54, 0x78, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x98, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x78, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x10,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x5d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x14, 0x54, 0x78, 0x6e, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x78, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x78, 0x6e,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x3d, 0x0a, 0x13, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x4a, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x22, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x2a, 0x1c, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x10,
	0x01, 0x2a, 0x25, 0x0a, 0x07, 0x54, 0x78, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x65, 0x63,
	0x79, 0x63, 0x6c, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x2a, 0x30, 0x0a, 0x08, 0x54, 0x78, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x32, 0xae, 0x05, 0x0a, 0x10, 0x41,
	0x70, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x52, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x6e,
	0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x49, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x78, 0x6e, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x6e, 0x12,
	0x11, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x54,
	0x78, 0x6e, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x07, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x78, 0x6e, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x49, 0x0a, 0x0d, 0x54, 0x78, 0x6e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x78, 0x6e,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x78, 0x6e, 0x12, 0x1c, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54,
	0x78, 0x6e, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x54, 0x78, 0x6e, 0x1a, 0x17, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x12, 0x22,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_device_app_proto_device_proto_rawDescOnce sync.Once
	file_device_app_proto_device_proto_rawDescData = file_device_app_proto_device_proto_rawDesc
)

func file_device_app_proto_device_proto_rawDescGZIP() []byte {
	file_device_app_proto_device_proto_rawDescOnce.Do(func() {
		file_device_app_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_app_proto_device_proto_rawDescData)
	})
	return file_device_app_proto_device_proto_rawDescData
}

var file_device_app_proto_device_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_device_app_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_device_app_proto_device_proto_goTypes = []interface{}{
	(EditType)(0),                      // 0: service.EditType
	(TxnType)(0),                       // 1: service.TxnType
	(TxnState)(0),                      // 2: service.TxnState
	(*Device)(nil),                     // 3: service.Device
	(*DeviceRelationEditRequest)(nil),  // 4: service.DeviceRelationEditRequest
	(*EditObj)(nil),                    // 5: service.EditObj
	(*DeviceRelationEditResponse)(nil), // 6: service.DeviceRelationEditResponse
	(*GetDevicesByEquipsRequest)(nil),  // 7: service.GetDevicesByEquipsRequest
	(*GetDevicesByEquipsResponse)(nil), // 8: service.GetDevicesByEquipsResponse
	(*DeviceInfo)(nil),                 // 9: service.DeviceInfo
	(*ModifySendTxnRequest)(nil),       // 10: service.ModifySendTxnRequest
	(*ActTxn)(nil),                     // 11: service.ActTxn
	(*CreateSendTxnRequest)(nil),       // 12: service.CreateSendTxnRequest
	(*CreateSendTxnResponse)(nil),      // 13: service.CreateSendTxnResponse
	(*ApplyTxn)(nil),                   // 14: service.ApplyTxn
	(*QueryTxnRequest)(nil),            // 15: service.QueryTxnRequest
	(*QueryTxnResponse)(nil),           // 16: service.QueryTxnResponse
	(*Comment)(nil),                    // 17: service.Comment
	(*TxnAddCommentRequest)(nil),       // 18: service.TxnAddCommentRequest
	(*MigrationTxnRequest)(nil),        // 19: service.MigrationTxnRequest
	(*CommonResponse)(nil),             // 20: service.CommonResponse
	(*RemoveTxnRequest)(nil),           // 21: service.RemoveTxnRequest
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
}
var file_device_app_proto_device_proto_depIdxs = []int32{
	5,  // 0: service.DeviceRelationEditRequest.actions:type_name -> service.EditObj
	0,  // 1: service.EditObj.act:type_name -> service.EditType
	9,  // 2: service.GetDevicesByEquipsResponse.devices:type_name -> service.DeviceInfo
	11, // 3: service.ModifySendTxnRequest.macList:type_name -> service.ActTxn
	0,  // 4: service.ActTxn.act:type_name -> service.EditType
	3,  // 5: service.ActTxn.device:type_name -> service.Device
	22, // 6: service.CreateSendTxnRequest.time:type_name -> google.protobuf.Timestamp
	3,  // 7: service.CreateSendTxnRequest.devices:type_name -> service.Device
	3,  // 8: service.CreateSendTxnResponse.device:type_name -> service.Device
	1,  // 9: service.QueryTxnRequest.type:type_name -> service.TxnType
	2,  // 10: service.QueryTxnRequest.state:type_name -> service.TxnState
	3,  // 11: service.QueryTxnResponse.devices:type_name -> service.Device
	17, // 12: service.QueryTxnResponse.comments:type_name -> service.Comment
	12, // 13: service.AppDeviceService.CreateSendTxn:input_type -> service.CreateSendTxnRequest
	10, // 14: service.AppDeviceService.ModifySendTxn:input_type -> service.ModifySendTxnRequest
	14, // 15: service.AppDeviceService.CancelSendTxn:input_type -> service.ApplyTxn
	15, // 16: service.AppDeviceService.ListTxn:input_type -> service.QueryTxnRequest
	18, // 17: service.AppDeviceService.TxnAddComment:input_type -> service.TxnAddCommentRequest
	19, // 18: service.AppDeviceService.MigrationTxn:input_type -> service.MigrationTxnRequest
	21, // 19: service.AppDeviceService.RemoveTxn:input_type -> service.RemoveTxnRequest
	14, // 20: service.AppDeviceService.ConfirmRecycle:input_type -> service.ApplyTxn
	7,  // 21: service.AppDeviceService.GetDevicesByEquips:input_type -> service.GetDevicesByEquipsRequest
	13, // 22: service.AppDeviceService.CreateSendTxn:output_type -> service.CreateSendTxnResponse
	20, // 23: service.AppDeviceService.ModifySendTxn:output_type -> service.CommonResponse
	20, // 24: service.AppDeviceService.CancelSendTxn:output_type -> service.CommonResponse
	16, // 25: service.AppDeviceService.ListTxn:output_type -> service.QueryTxnResponse
	20, // 26: service.AppDeviceService.TxnAddComment:output_type -> service.CommonResponse
	20, // 27: service.AppDeviceService.MigrationTxn:output_type -> service.CommonResponse
	20, // 28: service.AppDeviceService.RemoveTxn:output_type -> service.CommonResponse
	20, // 29: service.AppDeviceService.ConfirmRecycle:output_type -> service.CommonResponse
	8,  // 30: service.AppDeviceService.GetDevicesByEquips:output_type -> service.GetDevicesByEquipsResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_device_app_proto_device_proto_init() }
func file_device_app_proto_device_proto_init() {
	if File_device_app_proto_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_app_proto_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceRelationEditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceRelationEditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesByEquipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesByEquipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySendTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActTxn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSendTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSendTxnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyTxn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTxnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnAddCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_app_proto_device_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_app_proto_device_proto_goTypes,
		DependencyIndexes: file_device_app_proto_device_proto_depIdxs,
		EnumInfos:         file_device_app_proto_device_proto_enumTypes,
		MessageInfos:      file_device_app_proto_device_proto_msgTypes,
	}.Build()
	File_device_app_proto_device_proto = out.File
	file_device_app_proto_device_proto_rawDesc = nil
	file_device_app_proto_device_proto_goTypes = nil
	file_device_app_proto_device_proto_depIdxs = nil
}
