// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: device/app/proto/device.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditType int32

const (
	EditType_Add EditType = 0
	EditType_Del EditType = 1
)

// Enum value maps for EditType.
var (
	EditType_name = map[int32]string{
		0: "Add",
		1: "Del",
	}
	EditType_value = map[string]int32{
		"Add": 0,
		"Del": 1,
	}
)

func (x EditType) Enum() *EditType {
	p := new(EditType)
	*p = x
	return p
}

func (x EditType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditType) Descriptor() protoreflect.EnumDescriptor {
	return file_device_app_proto_device_proto_enumTypes[0].Descriptor()
}

func (EditType) Type() protoreflect.EnumType {
	return &file_device_app_proto_device_proto_enumTypes[0]
}

func (x EditType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditType.Descriptor instead.
func (EditType) EnumDescriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{0}
}

type AssignDevicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *AssignDevicesRequest) Reset() {
	*x = AssignDevicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDevicesRequest) ProtoMessage() {}

func (x *AssignDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDevicesRequest.ProtoReflect.Descriptor instead.
func (*AssignDevicesRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{0}
}

func (x *AssignDevicesRequest) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac   string `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type AssignDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Mac     string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AssignDeviceResponse) Reset() {
	*x = AssignDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDeviceResponse) ProtoMessage() {}

func (x *AssignDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDeviceResponse.ProtoReflect.Descriptor instead.
func (*AssignDeviceResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{2}
}

func (x *AssignDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignDeviceResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *AssignDeviceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeviceRelationEditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjID   string     `protobuf:"bytes,1,opt,name=objID,proto3" json:"objID,omitempty"`
	Actions []*EditObj `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *DeviceRelationEditRequest) Reset() {
	*x = DeviceRelationEditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceRelationEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRelationEditRequest) ProtoMessage() {}

func (x *DeviceRelationEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRelationEditRequest.ProtoReflect.Descriptor instead.
func (*DeviceRelationEditRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceRelationEditRequest) GetObjID() string {
	if x != nil {
		return x.ObjID
	}
	return ""
}

func (x *DeviceRelationEditRequest) GetActions() []*EditObj {
	if x != nil {
		return x.Actions
	}
	return nil
}

type EditObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Act      EditType `protobuf:"varint,1,opt,name=act,proto3,enum=service.EditType" json:"act,omitempty"`
	DeviceID string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
}

func (x *EditObj) Reset() {
	*x = EditObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditObj) ProtoMessage() {}

func (x *EditObj) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditObj.ProtoReflect.Descriptor instead.
func (*EditObj) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{4}
}

func (x *EditObj) GetAct() EditType {
	if x != nil {
		return x.Act
	}
	return EditType_Add
}

func (x *EditObj) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type DeviceRelationEditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeviceID string `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Error    string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeviceRelationEditResponse) Reset() {
	*x = DeviceRelationEditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceRelationEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRelationEditResponse) ProtoMessage() {}

func (x *DeviceRelationEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRelationEditResponse.ProtoReflect.Descriptor instead.
func (*DeviceRelationEditResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceRelationEditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeviceRelationEditResponse) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceRelationEditResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDevicesByEquipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipIDs []string `protobuf:"bytes,1,rep,name=equipIDs,proto3" json:"equipIDs,omitempty"`
}

func (x *GetDevicesByEquipsRequest) Reset() {
	*x = GetDevicesByEquipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesByEquipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesByEquipsRequest) ProtoMessage() {}

func (x *GetDevicesByEquipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesByEquipsRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesByEquipsRequest) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{6}
}

func (x *GetDevicesByEquipsRequest) GetEquipIDs() []string {
	if x != nil {
		return x.EquipIDs
	}
	return nil
}

type GetDevicesByEquipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipID string        `protobuf:"bytes,1,opt,name=equipID,proto3" json:"equipID,omitempty"`
	Devices []*DeviceInfo `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *GetDevicesByEquipsResponse) Reset() {
	*x = GetDevicesByEquipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesByEquipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesByEquipsResponse) ProtoMessage() {}

func (x *GetDevicesByEquipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesByEquipsResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesByEquipsResponse) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{7}
}

func (x *GetDevicesByEquipsResponse) GetEquipID() string {
	if x != nil {
		return x.EquipID
	}
	return ""
}

func (x *GetDevicesByEquipsResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MacAddress  string `protobuf:"bytes,2,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	State       string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Model       string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	OnlineState string `protobuf:"bytes,6,opt,name=onlineState,proto3" json:"onlineState,omitempty"`
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_app_proto_device_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_device_app_proto_device_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_device_app_proto_device_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DeviceInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DeviceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetOnlineState() string {
	if x != nil {
		return x.OnlineState
	}
	return ""
}

var File_device_app_proto_device_proto protoreflect.FileDescriptor

var file_device_app_proto_device_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x41, 0x0a, 0x14, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x06, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x58, 0x0a,
	0x14, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5d, 0x0a, 0x19, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x4f, 0x62, 0x6a, 0x52, 0x07, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x07, 0x45, 0x64, 0x69, 0x74, 0x4f, 0x62,
	0x6a, 0x12, 0x23, 0x0a, 0x03, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x03, 0x61, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x44, 0x22, 0x68, 0x0a, 0x1a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x37, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x49, 0x44, 0x73, 0x22, 0x65, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x44, 0x12, 0x2d, 0x0a,
	0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xac, 0x01, 0x0a,
	0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x1c, 0x0a, 0x08, 0x45,
	0x64, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x10, 0x01, 0x32, 0x8e, 0x03, 0x0a, 0x10, 0x41, 0x70,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51,
	0x0a, 0x0d, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x60, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x45, 0x64, 0x69, 0x74, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x62, 0x0a, 0x13, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x64, 0x69, 0x74, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x12, 0x22, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_device_app_proto_device_proto_rawDescOnce sync.Once
	file_device_app_proto_device_proto_rawDescData = file_device_app_proto_device_proto_rawDesc
)

func file_device_app_proto_device_proto_rawDescGZIP() []byte {
	file_device_app_proto_device_proto_rawDescOnce.Do(func() {
		file_device_app_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_app_proto_device_proto_rawDescData)
	})
	return file_device_app_proto_device_proto_rawDescData
}

var file_device_app_proto_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_device_app_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_device_app_proto_device_proto_goTypes = []interface{}{
	(EditType)(0),                      // 0: service.EditType
	(*AssignDevicesRequest)(nil),       // 1: service.AssignDevicesRequest
	(*Device)(nil),                     // 2: service.Device
	(*AssignDeviceResponse)(nil),       // 3: service.AssignDeviceResponse
	(*DeviceRelationEditRequest)(nil),  // 4: service.DeviceRelationEditRequest
	(*EditObj)(nil),                    // 5: service.EditObj
	(*DeviceRelationEditResponse)(nil), // 6: service.DeviceRelationEditResponse
	(*GetDevicesByEquipsRequest)(nil),  // 7: service.GetDevicesByEquipsRequest
	(*GetDevicesByEquipsResponse)(nil), // 8: service.GetDevicesByEquipsResponse
	(*DeviceInfo)(nil),                 // 9: service.DeviceInfo
}
var file_device_app_proto_device_proto_depIdxs = []int32{
	2, // 0: service.AssignDevicesRequest.devices:type_name -> service.Device
	5, // 1: service.DeviceRelationEditRequest.actions:type_name -> service.EditObj
	0, // 2: service.EditObj.act:type_name -> service.EditType
	9, // 3: service.GetDevicesByEquipsResponse.devices:type_name -> service.DeviceInfo
	1, // 4: service.AppDeviceService.AssignDevices:input_type -> service.AssignDevicesRequest
	4, // 5: service.AppDeviceService.DeviceProjectEdit:input_type -> service.DeviceRelationEditRequest
	4, // 6: service.AppDeviceService.DeviceEquipmentEdit:input_type -> service.DeviceRelationEditRequest
	7, // 7: service.AppDeviceService.GetDevicesByEquips:input_type -> service.GetDevicesByEquipsRequest
	3, // 8: service.AppDeviceService.AssignDevices:output_type -> service.AssignDeviceResponse
	6, // 9: service.AppDeviceService.DeviceProjectEdit:output_type -> service.DeviceRelationEditResponse
	6, // 10: service.AppDeviceService.DeviceEquipmentEdit:output_type -> service.DeviceRelationEditResponse
	8, // 11: service.AppDeviceService.GetDevicesByEquips:output_type -> service.GetDevicesByEquipsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_device_app_proto_device_proto_init() }
func file_device_app_proto_device_proto_init() {
	if File_device_app_proto_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_app_proto_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignDevicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceRelationEditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceRelationEditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesByEquipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesByEquipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_app_proto_device_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_app_proto_device_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_app_proto_device_proto_goTypes,
		DependencyIndexes: file_device_app_proto_device_proto_depIdxs,
		EnumInfos:         file_device_app_proto_device_proto_enumTypes,
		MessageInfos:      file_device_app_proto_device_proto_msgTypes,
	}.Build()
	File_device_app_proto_device_proto = out.File
	file_device_app_proto_device_proto_rawDesc = nil
	file_device_app_proto_device_proto_goTypes = nil
	file_device_app_proto_device_proto_depIdxs = nil
}
